FROM python:3.12

ENV PYTHONPATH=/app:$PYTHONPATH
WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock* /app/

RUN poetry config virtualenvs.create false
RUN poetry install --no-root

COPY ./apps/worker /app/

CMD ["celery", "-A", "run", "worker", "-Q", "sum-queue,beat-queue", "--hostname", "worker@%h", "-c", "4", "--loglevel=info"]