services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: celery-tutorial-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:alpine
    container_name: celery-tutorial-redis
    ports:
      - "6379:6379"