FROM python:3.10

ENV PYTHONPATH=/app:$PYTHONPATH

WORKDIR /app
RUN pip install poetry

COPY pyproject.toml poetry.lock* /app/

RUN poetry config virtualenvs.create false
RUN poetry install --no-root

COPY ./apps/beat /app/

CMD ["celery", "-A", "run", "beat", "--loglevel=info"]